### ISSUE TITLE
Mini-Sports1M dataset and FCVID dataset

### ISSUE THREAD

**Issue by jpthu17** [IBM/AdaMML#1]
Could you share Mini-Sports1M dataset and FCVID dataset? Because I can't find them on the Internet.

**Comment by jpthu17** [comment]
Or could you share video frames and audio extracted from Mini-Sports1M dataset and FCVID dataset?

**Comment by rpand002** [comment]
The raw video frames and audio extracted from both Mini-Sports1M and FCVID dataset are very large in size. So, it’s not possible to share them through any cloud platform. However, for Mini-Sports1M, you can use the attached two files for downloading the videos directly from YouTube. Hope it helps!

[test_minisports1m.txt](https://github.com/IBM/AdaMML/files/7563741/test_minisports1m.txt)
[train_minisports1m.txt](https://github.com/IBM/AdaMML/files/7563742/train_minisports1m.txt)

**Comment by sherlockfeng1995** [comment]
Could  you  tell  me  how  to  obtain  kinetics-sound  dataset?

**Comment by rpand002** [comment]
Hi @sherlockfeng1995: we obtained the kinetics-sounds dataset from the original Kinetics400 dataset. Kinetics-Sounds is actually a subset of Kinetics dataset and consists of 22,521 videos for training and 1,532 videos testing across 31 action classes. Here are the 31 action classes: 

> blowing nose, blowing out candles, bowling, chopping wood, dribbling basketball, laughing, mowing lawn, playing accordion, playing bagpipes, playing bass guitar, playing clarinet, playing drums, playing guitar, playing harmonica, playing keyboard, playing organ, playing piano, playing saxophone, playing trombone, playing trumpet, playing violin, playing xylophone, ripping paper, shoveling snow, shuffling cards, singing, stomping grapes, tap dancing, tapping guitar, tapping pen, and tickling.

**Comment by qwangku** [comment]
@rpand002 Thanks for sharing. I downloaded mp4 files based on test_minisports1m.txt and used extract_rgb.py to extract frames from the videos.  Can you share the script that converted the folders generated by extract_rgb.py to lmdv?
