### ISSUE TITLE
The training details about unimodal pretrained model

### ISSUE THREAD

**Issue by weizequan** [IBM/AdaMML#2]
Hi, the whole Adamml model needs the unimodal pretrained models. However, there is no details about this in this project or your paper. Could you please share these details about training the unimodal models. Thanks a lot.

**Comment by rpand002** [comment]
Hi @weizequan: sorry for the delayed response. We have now added the details for training unimodal models. You can check the README for example commands (https://github.com/IBM/AdaMML#training-unimodal-models).
