### ISSUE TITLE
Missing categories in Kinetics-Sound Dataset

### ISSUE THREAD

**Issue by Coder-Liuu** [IBM/AdaMML#3]
Which three categories are missing from the Kinetics-Sounds dataset? I can't find the details in paper

**Comment by rpand002** [comment]
Hello, thanks for your interest in our work. Here are the 31 categories of the Kinetics-Sounds dataset: 

> blowing nose, blowing out candles, bowling, chopping wood, dribbling basketball, laughing, mowing lawn, playing accordion, playing bagpipes, playing bass guitar, playing clarinet, playing drums, playing guitar, playing harmonica, playing keyboard, playing organ, playing piano, playing saxophone, playing trombone, playing trumpet, playing violin, playing xylophone, ripping paper, shoveling snow, shuffling cards, singing, stomping grapes, tap dancing, tapping guitar, tapping pen, and tickling.

**Comment by Coder-Liuu** [comment]
Thanks very much.:smile:

**Comment by Akiraxty** [comment]
> Thanks very much.😄

Hi~I am follow this job too. I would appreciate it very much if you share Kinetics-Sounds dataset. Have a nice day!
