### ISSUE TITLE
About the training speed of ActivityNet1.3

### ISSUE THREAD

**Issue by Coder-Liuu** [IBM/AdaMML#4]
I would like to ask you how many epochs it takes to retrain ActivityNet1.3 because I train my own model to grow too slowly

**Comment by rpand002** [comment]
We first used 70 epochs to train the unimodality models (with ImageNet weights) on ActivityNet dataset. For training the AdaMML models, we fix the policy network and “warm up” the recognition network using the trained unimodality models for 5 epochs to provide a good starting point for policy learning. We then alternatively train both policy and recognition networks for 20 epochs and then fine-tune the recognition network with a fixed policy network for another 10 epochs. See Training Details in Section 4.1 of the paper for more details.

**Comment by Coder-Liuu** [comment]
Thanks very much. :satisfied:
